### ISSUE TITLE
Cannot get getByte of Null

### ISSUE THREAD

**Issue by microshine** [indutny/brorand#6]
I'm trying to use `elliptic.js` in WebWorker. And I've got this error.
```
TypeError: Не удалось получить свойство "getByte" ссылки, значение которой не определено или является NULL
   at _rand (http://localhost:3000/worker/elliptic.js:7493:9)
   at generate (http://localhost:3000/worker/elliptic.js:7456:3)
   at rand (http://localhost:3000/worker/elliptic.js:7447:3)
   at genKeyPair (http://localhost:3000/worker/elliptic.js:5654:3)
   at Anonymous function (http://localhost:3000/worker/webcrypto-liner.js:3269:14)
   at u (http://localhost:3000/worker/promise.min.js:1:618)
   at v (http://localhost:3000/worker/promise.min.js:1:1801)
   at f (http://localhost:3000/worker/promise.min.js:1:853)
   at EcCrypto.generateKey (http://localhost:3000/worker/webcrypto-liner.js:3262:10)
   at Anonymous function (http://localhost:3000/worker/webcrypto-liner.js:2148:14)
```

I fixed this problem by 
- changing `window` to `self` https://github.com/indutny/brorand/blob/master/index.js#L19, cause some browsers allows to use `crypto` from WebWorker
- adding`pseudoRandomBytes` function if `crypto.getRandomValues` is not allowed

**Comment by fanatid** [comment]
о_О ошибки на русском? это потому что браузер использует локаль ru_RU?

**Comment by microshine** [comment]
В данном случае ошибка больше связана с функцией генерации случайных чисел )

**Comment by fanatid** [comment]
я про текст ошибки, не подозревал что на них тоже есть перевод: "Не удалось получить свойство "getByte" ссылки, значение которой не определено или является NULL"

**Comment by microshine** [comment]
https://github.com/microshine/liner-example/blob/master/worker/elliptic.js#L7459

**Comment by indutny** [comment]
Is there something that can be fixed? Or is it a won't fix?

**Comment by microshine** [comment]
I think it wold be better to change window to self

**Comment by indutny** [comment]
Ah, alright. This is already fixed in https://github.com/indutny/brorand/commit/a06c49d513e212b1d6870b8a8ed266292110bbed and released in 1.0.7!

**Comment by microshine** [comment]
@indutny thank you
